#!/usr/bin/env bash

# Este script obtiene y calcula el promedio de los querytime (tiempo que demora en obtener la ip) de las 9 URL que se ven a continuacion

url1=www.turismo.navarra.es
url2=www.warnerbros.com
url3=www.ligabancomer.mx
url4=www.london.lecool.com
url5=www.afl.com.au
url6=www.youtube.com
url7=www.allocine.fr
url8=www.larepublica.pe
url9=www.akirayamaoka.jp
url9=www.dropkickmurphys.com
url9=www.koreatimes.co.kr

Total_tiempo=0 # Variable donde se ira almacenando la suma de los query time de cada URL

# Realiza el proceso para la PRIMERA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url1 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string1+=${dns_out:k:1}

			done

	else

		time_string1=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

num=0123456789

for i in $(seq 13 ${#time_string1})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string1:i-1:1}" == "${num:j:1}" ]

					then

						time1+=${time_string1:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la SEGUNDA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url2 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string2+=${dns_out:k:1}

			done

	else

		time_string2=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

for i in $(seq 13 ${#time_string2})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string2:i-1:1}" == "${num:j:1}" ]

					then

						time2+=${time_string2:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la TERCERA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url3 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string3+=${dns_out:k:1}

			done

	else

		time_string3=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

for i in $(seq 13 ${#time_string3})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string3:i-1:1}" == "${num:j:1}" ]

					then

						time3+=${time_string3:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la CUARTA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url4 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string4+=${dns_out:k:1}

			done

	else

		time_string4=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

for i in $(seq 13 ${#time_string4})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string4:i-1:1}" == "${num:j:1}" ]

					then

						time4+=${time_string4:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la QUINTA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url5 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string5+=${dns_out:k:1}

			done

	else

		time_string5=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

for i in $(seq 13 ${#time_string5})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string5:i-1:1}" == "${num:j:1}" ]

					then

						time5+=${time_string5:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la SEXTA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url6 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string6+=${dns_out:k:1}

			done

	else

		time_string6=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

for i in $(seq 13 ${#time_string6})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string6:i-1:1}" == "${num:j:1}" ]

					then

						time6+=${time_string6:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la SEPTIMA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url7 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string7+=${dns_out:k:1}

			done

	else

		time_string7=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

num=0123456789

for i in $(seq 13 ${#time_string7})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string7:i-1:1}" == "${num:j:1}" ]

					then

						time7+=${time_string7:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la OCTAVA URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url8 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string8+=${dns_out:k:1}

			done

	else

		time_string8=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig


for i in $(seq 13 ${#time_string8})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string8:i-1:1}" == "${num:j:1}" ]

					then

						time8+=${time_string8:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Realiza el proceso para la Novena URL

# Corre el comando dig para obtener el querytime y almacena resultado en variable

dns_out=$(dig $url9 +noall +stats | head -5 | tail -2)

# Algunas paginas web devuelven un warning dentro del string pero de todas formas devuelven el querytime, el siguiente bloque elimina el warning
# del string

if [ "${dns_out:3:1}" == "Q" ]

	then

		for k in $(seq 0 31)

			do

				time_string9+=${dns_out:k:1}

			done

	else

		time_string9=$dns_out

fi

# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

num=0123456789

for i in $(seq 13 ${#time_string9})

	do

		for j in $(seq 0 ${#num})

			do

				if [ "${time_string9:i-1:1}" == "${num:j:1}" ]

					then

						time9+=${time_string9:i-1:1}

				fi

			done

	done

# Fin del bloque que extrae el querytime del string devuelto por el comando dig

# Calculo el promedio de los 10 tiempos

Total_tiempo=$((time1 + time2 + time3 + time4 + time5 + time6 + time7 + time8 + time9))

Promedio_tiempo=$((Total_tiempo/9))

echo $Promedio_tiempo