#!/usr/bin/env bash

# Este script obtiene y calcula el promedio de los querytime (tiempo que demora en obtener la ip) de las 9 URL que se ven a continuacion

url1=www.turismo.navarra.es
url2=www.koreatimes.co.kr
url3=www.ligabancomer.mx
url4=www.google.com
url5=www.afl.com.au
url6=www.youtube.com
url7=www.allocine.fr
url8=www.larepublica.pe
url9=www.akirayamaoka.jp
Total_tiempo=0 # Variable donde se ira almacenando la suma de los query time de cada URL

error=0

for o in {1..9}

	do

		if [ "$error" == 0 ]

			then

			# Corre el comando dig para obtener el querytime y almacena resultado en variable

			url_a_usar=url$o

			dns_out=$(dig ${!url_a_usar} +noall +stats +answer)

			encontre=1

			u=0

				while [ $encontre != 2 ]

					do

						if [ "${dns_out:u:1}" != "+" ] && [ $u -le ${#dns_out} ]

							then

								u=$((u+1))


							else
				
								if [ "${dns_out:u+1:1}" == "c" ] && [ $u -le ${#dns_out} ]

									then 

										if [ "${dns_out:u+2:1}" == "m" ] && [ $u -le ${#dns_out} ]

											then
									
												if [ "${dns_out:u+3:1}" == "d" ] && [ $u -le ${#dns_out} ]

													then encontre=2

													else u=$((u+1))

												fi

											else u=$((u+1))
										fi

									else u=$((u+1))
								fi
						fi


					done


			if [ "${dns_out:u+5:1}" == "w" ] && [ $u -le ${#dns_out} ]

				then 
					error=0

				else
					error=1
					Promedio_tiempo=$((-1 * o))

			fi

			encontre=1

				while [ "$encontre" != 2 ]

					do

						if [ "${dns_out:u:1}" != "Q" ] && [ $u -le ${#dns_out} ]

							then

								u=$((u+1))

							else
				
								if [ "${dns_out:u+1:1}" == "u" ] && [ $u -le ${#dns_out} ]

									then encontre=2

									else u=$((u+1))
								fi
									

						fi


					done

			# Inicio del bloque que extrae el querytime del string devuelto por el comando dig

			num=0123456789

			while [ "${dns_out:u:1}" != ";" ]

				do

					for j in $(seq 0 ${#num})
	
						do

							if [ "${dns_out:u:1}" == "${num:j:1}" ]

								then

									time+=${dns_out:u:1}

							fi

						done

					u=$((u+1))
	
				done

			
			# Fin del bloque que extrae el querytime del string devuelto por el comando dig

			#echo $time
			Total_tiempo=$((time+Total_tiempo))
			time=""
			dns_out=""

			fi

	done

# Calculo el promedio de los 9 tiempos

if [ "$error" == 0 ]

	then

		Promedio_tiempo=$((Total_tiempo/9))

	fi

echo $Promedio_tiempo
